resolver: lts-24.8
#resolver: nightly-2018-11-29
packages:
- '.'

extra-deps:
- git: https://github.com/dorchard/type-level-sets
  commit: d71becf49c092cd7697f39e4f4fb55b289af3d31
#- ../type-level-sets
flags: {}
#allow-newer: true
